"""empty message

Revision ID: 32d01f8b2cf4
Revises: e0efff56b542
Create Date: 2025-01-17 17:30:20.277274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d01f8b2cf4'
down_revision = 'e0efff56b542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('joindate',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('joindate',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
